version: "3"
services:
  app:
    platform: "linux/amd64"
    container_name: crmsystem
    build: ./docker/app
    volumes:
      - .:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    restart: always
    ports:
      - 5173:5173
    networks:
      - test_db

  nginx:
    platform: "linux/amd64"
    image: nginx
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    restart: always
    networks:
      - test_db

networks:
  test_db:
    external: true
